@extends('layouts.admin')
@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content"><div class="post d-flex flex-column-fluid" id="kt_post"><div id="kt_content_container" class="container-xxl">
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="card"><div class="card-header border-0 pt-6"><div class="card-title"><div class="position-relative"><input id="speciality-search" class="form-control form-control-solid w-250px" placeholder="Search specialities"></div></div><div class="card-toolbar"><a class="btn btn-primary" href="{{ route('admin.specialities.add_edit_form') }}"><i class="bi bi-plus-lg"></i>Add Speciality</a></div></div>
    <div class="card-body pt-0"><table class="table" id="speciality-table"><thead><tr><th>Name</th><th>Description</th><th>Status</th><th>Actions</th></tr></thead><tbody></tbody></table></div></div>
</div></div></div>
@endsection
@push('scripts')
<script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script>KTUtil.onDOMContentLoaded(function(){const escape=v=>$('<div>').text(v??'').html();const table=$('#speciality-table').DataTable({processing:true,serverSide:true,ajax:{url:'{{ route('admin.specialities.datatable') }}',data:d=>d.search_term=document.getElementById('speciality-search').value.trim()},columns:[{data:'name',render:escape},{data:'description',render:v=>escape(v||'—')},{data:'status',render:(v,t,r)=>`<label class="form-check form-switch"><input class="form-check-input speciality-status" data-id="${r.id}" type="checkbox" ${v==='active'?'checked':''}></label>`},{data:'id',orderable:false,render:id=>`<a class="btn btn-sm" href="{{ route('admin.specialities.add_edit_form') }}/${id}"><i class="bi bi-pencil-fill"></i></a><button class="btn btn-sm speciality-delete" data-id="${id}"><i class="bi bi-trash"></i></button>`}]});let timer;$('#speciality-search').on('input',()=>{clearTimeout(timer);timer=setTimeout(()=>table.ajax.reload(),500);});document.addEventListener('change',e=>{if(!e.target.matches('.speciality-status'))return;const box=e.target;$.post('{{ route('admin.specialities.status_change',':id') }}'.replace(':id',box.dataset.id),{_token:'{{ csrf_token() }}'}).fail(()=>box.checked=!box.checked);});document.addEventListener('click',e=>{const button=e.target.closest('.speciality-delete');if(!button)return;Swal.fire({text:'Delete this speciality?',icon:'warning',showCancelButton:true,confirmButtonText:'Yes, delete'}).then(r=>{if(r.isConfirmed)$.post('{{ route('admin.specialities.delete',':id') }}'.replace(':id',button.dataset.id),{_token:'{{ csrf_token() }}'}).done(()=>table.ajax.reload(null,false));});});});</script>
@endpush
